version: '3'
services:
  postgresql:
    image: postgres:13.4-alpine
    ports:
      - "5454:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=krugerInventario